about_me/urls.py
from django.urls import path
from about_me.views import (
    my_projects, 
    contact, 
)

app_name = "about_me"



urlpatterns = [
    path("", my_projects, name="my_projects"),
    path("contact/", contact, name="contact"),
]

porfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("about_me.urls", namespace="about_me"))
]

about_me/models.py
from django.db import models
from django.utils import timezone


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.email


class CollectTraffic(models.Model):
    ip = models.CharField(max_length=100)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.ip

about_me/forms.py
from django import forms
from about_me.models import Contact



class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = ["name", "email", "message"]

about_me/views.py
from django.shortcuts import render, redirect
from about_me.forms import ContactForm
from django.contrib import messages
from utils.send_email import send_email
from django.http import JsonResponse
from .models import Contact, CollectTraffic
import json



def my_projects(request):
    remote_addr = request.META.get('REMOTE_ADDR')
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    
    excluded_ip = ['127.0.0.1', '35.173.69.207', '192.168.1.155']
    
    ip = ''

    if remote_addr and remote_addr not in excluded_ip:
        ip = remote_addr
    if x_forwarded_for and x_forwarded_for not in excluded_ip:
        ip = x_forwarded_for.split(',')[0].strip()

    if ip:
        CollectTraffic.objects.create(ip=ip)
    
    return render(request, "about_me/my_projects.html")


def contact(request):
    data = json.loads(request.body.decode('utf-8'))
    
    if request.method == "POST":
        if data['name'] and data['email'] and data['message']:

            Contact.objects.create(
                    name=data['name'],
                    email=data['email'],
                    message=data['message']
                )
            message = """
                    Thank you very much for the message. 
                    I will contact you as soon as possible. 
                    Once again, thank you very much. Sincerly, Eric Anderson
                """
            send_email(
                request, 
                email = data['email'],
                name = data['name']
            )
            return JsonResponse(data={'message': message}, status=200)
        else:
            error_message = "Sorry, your message did not send. Please try again!"
        return JsonResponse(data={'error':error_message}, status=400)
    
    return redirect('about_me:my_projects')

    

about_me/templates/about_me/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link type="text/css" rel="stylesheet" href="{% static 'about_me/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'about_me/style.css' %}">
    <title>
    {% block title %}
    {% endblock title %}
    </title>

    <style>
        .form-content {
            margin-top: 1rem;
        }
        p > label {
            display: none;
        }
        p > input, textarea {
            display: block;
            width: 100%;
            padding: 0.7rem;
            outline: none;
            border: none;
            margin-top: 0rem;
            border-radius: 5px;
            margin-bottom: 0.7rem;
        }
        /* p > textarea {
            margin-top: 1rem;
        } */
    </style>
</head>
<body>
    <header id="header">
        <nav class="nav-mobile">
            <div class="nav-buttons">
                <i class="fa fa-bars"></i>
                <i class="fa fa-times"></i>
            </div>
            <div class="brand">
                <a class="brand-name-link" href="{% url 'about_me:home' %}" class="brand-name">Digital <span>Samurai</span></a>
            </div>
            <ul class="nav-items-mobile">
                <li class="nav-item"><a href="#main">Portfolio</a></li>
                <li class="nav-item"><a href="">Collaborate</a></li>
                <li class="nav-item"><a href="#footer">Contact</a></li>
            </ul>
        </nav>
        <div class="header">
            {% block message %}
            {% endblock message %}
            <div class="header-text">
                <h1 class="header-title">Building digital products, brands and 
                    <span>experience.</span>
                </h1>
                <p class="header-para">
                    A <strong>front-end & back-end developer</strong> in Philippines,
                    based out of San Diego, California USA. I specialize in Django Framework,
                    UX/UI, Responsive Web Design and Visual Development.
                </p>
                <a href="#" class="header-hire-me-btn">Hire Me</a>
            </div>
            <div class="header-img">
                <img src="{% static 'about_me/images/header_img.jpg' %}" alt="">
            </div>
        </div>
        <nav class="nav">
            <div class="brand">
                <a class="brand-name-link" href="{% url 'about_me:home' %}" class="brand-name">Digital <span>Samurai</span></a>
            </div>
            <ul class="nav-items">
                <li class="nav-item"><a href="#portfolio">Portfolio</a></li>
                <li class="nav-item"><a href="">Collaborate</a></li>
                <li class="nav-item"><a href="#footer">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main id="main">
    {% block content %}

    {% endblock content %}
    </main>

    <footer>
        <div class="scroll-up-button">
            <a href="#header"><i class="fas fa-chevron-up"></i></a>
        </div>

        <div id="footer" class="footer">
            <div class="personal-info">
                <div class="photo-of-me">
                    <img src="{% static 'about_me/images/me.jpg' %}" alt="">
                </div>
                <h2 class="my-name">Eric Anderson</h2>
                <p class="info-text">I'm front-end & back-end developer. I also specialize in 
                    Visual Development and UI/UX design.
                </p>
                <h2 class="email-me">Email me</h2>
                <a class="my-email" href="mailto:shinhosuck1973@gamil.com">shinhosuck1973@gamil.com</a>
            </div>
            <div class="contact-me">
                <h2 class="contact-title">Contact me</h2>
                <p class="contact-text">Looking forward to building something together!</p>
                <form class="form-content" action="{% url 'about_me:contact' %}" method="POST">
                    {% csrf_token %}
                    <!-- <input type="email" placeholder="please enter your email">
                    <textarea placeholder="please enter your message"></textarea> -->
                    {{ form.as_p }}
                    <button type="submit">Let's Connect</button>
                </form>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="{% static 'about_me/main.js' %}"></script>

    <script>

        const faBars = document.querySelector(".fa-bars")
        const faTimes = document.querySelector(".fa-times")
        const navItemsMobile = document.querySelector(".nav-items-mobile")
        const scrollUpButton = document.querySelector(".scroll-up-button")

        faBars.addEventListener("click", function(){
            faBars.style.display = "none"
            navItemsMobile.classList.add("show-nav-items-mobile")
            faTimes.style.display = "block"
            document.body.style.overflow = "hidden"
        })

        faTimes.addEventListener("click", function(){
            faBars.style.display = "block"
            navItemsMobile.classList.remove("show-nav-items-mobile")
            faTimes.style.display = "none"
            document.body.style.overflow = "scroll"
            
        })

        window.addEventListener("resize", function(){
            if (window.innerWidth <= 720) {
                    navItemsMobile.classList.remove("show-nav-items-mobile")
                    faTimes.style.display = "none"
                    faBars.style.display = "block"
            }
        })

        window.addEventListener("scroll", function(){
            if (window.scrollY > 0) {
                navItemsMobile.classList.remove("show-nav-items-mobile")
                scrollUpButton.classList.add("show-scroll-up-button")
                faBars.style.display = "block"
                faTimes.style.display = "none"
                document.body.style.overflow = "scroll"
                
            }
            else{
                scrollUpButton.classList.remove("show-scroll-up-button")
            }
        })
        
        const idEmail = document.querySelector("#id_email")
        const idMessage = document.querySelector("#id_message")
        idEmail.placeholder = "Please enter your email"
        idMessage.placeholder = "Please enter your message"
    </script>
</body>
</html>

about_me/templates/about_me/footer.html
<div id="contact-me" class="footer-conainer">
    <div class="contact-info">
        <div class="footer-header-container">
            <h1 class="footer-header">Contact</h1>
            <p>
                I would love to hear about your project and how I could help. 
                Please contact me via email, phone, or by messaging me using the form, 
                and I'll get back to you as soon as possible. Thank you very much.
            </p>
        </div>
        <div class="contact-container">
            <div class="message-form-container">
                <form class="message-form" action="{% url 'about_me:contact' %}" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <button class="contact-submit" type="submit">Send Message</button>
                </form>
            </div>
            <a href="mailto:shinhosuck1973@gmail.com" class="email-container">
                <div class="email">
                    <i class="fa fa-envelope"></i>
                    Email 
                </div>
                <span id="email">shinhosuck1973@gmail.com</span>
            </a>
            <a href="https://www.whatsapp.com/" target="_blank" class="phone-number-container">
                <div class="phone">
                    <i class="fa-brands fa-whatsapp"></i>
                    WhatsApp
                </div>
                <span id="phone">+63 969 352 7097</span>
            </a>
        </div>
    </div>
</div>
<div class="footer-container-2">
    <div class="social-links-container">
        <div class="social-links">
            <a href="https://github.com/shinhosuck" target="_blank"><i class="fab fa-github"></i></a>
            <a href="https://www.linkedin.com/in/eric-anderson-a6b906214/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
        </div>
    </div>
</div>

about_me/templates/about_me/home.html
{% extends "about_me/base.html"%}
{% load static %}


<title>
{% block title %}
    My Portfolio
{% endblock title %}
</title>

{% block message %}
    {% if messages %}
        {% for message in messages %}
            <h2 class="message">{{ message }}</h2>
        {% endfor%}
    {% endif %}
{% endblock message %}

{% block content %}
<div id="portfolio" class="my-portfolio">
    <h1 class="portfolio-title">My Portfolio <span>click image for more</span></h1>
    <div class="portfolio-cards">
        <div class="portfolio-content">
            <a class="portfolio-image" href="https://aiaiestore.herokuapp.com/" target="_blank">
                <img src="{% static 'about_me/images/project_img1.png' %}" alt="">
                <div class="porfolio-image-color-overlay portfolio-first-image">
                    <i class="fa fa-search"></i>
                </div>
            </a>
            <h2 class="card-title">E-commerce</h2>
            <p class="card-text">A front-end & back-end project for an e-commerce
                website using django framework.
            </p>
        </div>
        <div class="portfolio-content">
            <a class="portfolio-image" href="https://pawpalblog.herokuapp.com/" target="_blank" >
                <img src="{% static 'about_me/images/project_img2.png' %}" alt="">
                <div class="porfolio-image-color-overlay">
                    <i class="fa fa-search"></i>
                </div>
            </a>
            <h2 class="card-title" >Pet Blog</h2>
            <p class="card-text">A front-end & back-end project for a pet blog
                website using django framework.
            </p>
        </div>
        <div class="portfolio-content">
            <a class="portfolio-image" href="https://mydjangomusic.herokuapp.com/" target="_blank">
                <img src="{% static 'about_me/images/project_img3.png' %}" alt="">
                <div class="porfolio-image-color-overlay">
                    <i class="fa fa-search"></i>
                </div>
            </a>
            <h2 class="card-title">Cloud Music</h2>
            <p class="card-text">A front-end & back-end project for a cloud music
                website using django framework.
            </p>
        </div>
    </div>
</div>
<div id="work" class="work-inquire">
    <div class="work-inqure-text-content">
        <h2 class="work-inquire-title">Work Inquiry</h2>
        <p class="work-inquire-text">I'm always open to dicussing your project,
            improving your online presence or
            helping you with your brand.
        </p>
    </div>
    <div class="work-inquire-button">
        <a href="#">Let's Talk</a>
    </div>
</div>
{% endblock content %}

about_me/templates/about_me/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"> 
    <!-- google font -->

    <link rel="shortcut icon" href="{% static 'about_me/images/favicon.ico' %}"/>

    <link type="text/css" rel="stylesheet" href="{% static 'about_me/fa-font/css/all.min.css' %}">
    <!-- font awesome css -->

    <link rel="stylesheet" type="text/css" href="{% static 'about_me/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'about_me/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'about_me/footer.css' %}">
    <!-- style css -->
    
    <title>
    {% block title %}
        Portfolio
    {% endblock title %}
    </title>
</head>
<body>
   <header>
    {% include "about_me/nav.html" %}
   </header>
   <main>
    <div class="message-received-container">
        <button class="message-received-close-btn">
            <i class="fa fa-times"></i>
        </button>
        <h3 class="received-message"></h3>
    </div>

     {% block content %}
     {% endblock content %}

   </main>
    <footer>
        {% include "about_me/footer.html" %}
    </footer>


    <script type="text/javascript" src="{% static 'about_me/main.js' %}"></script>
</body>
</html>

about_me/templates/about_me/my_projects.html
{% extends 'about_me/index.html' %}
{% load static %}

    {% block title %}
        Projects
    {% endblock title %}

       
{% block content %}
<div class="tech-stack-main">
    <div class="tech-stack-container">
        <div class="projects-header-container tech-stack-header-container">
            <h1 class="project-header">Skills</h1>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/python.png' %}" alt="python">
                </div>
                <h2 class="tech-stack-header">Python</h2>
            </div>
            <p class="tech-stack-content">3 Years of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/django.png' %}" alt="django">
                </div>
                <h2 class="tech-stack-header">Django</h2>
            </div>
            <p class="tech-stack-content">3 Years of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image drf-image">
                    <img src="{% static 'about_me/images/skills_images/drf.jpg' %}" alt="drf">
                </div>
                <h2 class="tech-stack-header" style="display:grid">
                    DRF
                </h2>
            </div>
            <p class="tech-stack-content">1 Year of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/html.png' %}" alt="html">
                </div>
                <h2 class="tech-stack-header">HTML</h2>
            </div>
            <p class="tech-stack-content">3 Years of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/css.png' %}" alt="html">
                </div>
                <h2 class="tech-stack-header">CSS</h2>
            </div>
            <p class="tech-stack-content">3 Years of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/js.png' %}" alt="html">
                </div>
                <h2 class="tech-stack-header">JavaScript</h2>
            </div>
            <p class="tech-stack-content">2 Years of Experience</p>
        </div>
        <div class="tech-stack-text">
            <div class="tech-stack-image-and-header">
                <div class="tech-stack-image">
                    <img src="{% static 'about_me/images/skills_images/react.png' %}" alt="html">
                </div>
                <h2 class="tech-stack-header">React</h2>
            </div>
            <p class="tech-stack-content">1 Year of Experience</p>
        </div>
    </div>
</div>

<div class="projects-main">
    <div id="projects" class="projects">
        <div class="projects-header-container">
            <h1 class="project-header">Projects</h1>
        </div>

        <div class="project">
            <div class="project-img-wrapper">
                <img class="lg-image" src="{% static 'about_me/images/projects_images/pet-blog.webp' %}" alt="">
                <img class="sm-image" src="{% static 'about_me/images/projects_images/small-pet-blog.webp' %}" alt="">
                <div class="img-color-overlay"></div>
            </div>
            <div class="project-text-wrapper">
                <h3 class="project-name-header">
                    <span class="project-name">Pet Blog</span>
                    <span class="project-name-divider">|</span>
                    <span class="project-date">May 2024</span>
                </h3>
                <div class="project-tech-stacks-container">
                    <h4 class="project-tech-stack">Tech Stacks</h4>
                    <ul class="tech-stacks-used">
                        <li>Python,</li>
                        <li>Django,</li>
                        <li>DRF,</li>
                        <li>React,</li>
                        <li>HTML,</li>
                        <li>CSS</li>
                    </ul>
                </div>
                <div class="project-view-code-container">
                    <a class='view-code' href="https://github.com/shinhosuck/django-reactjS-pet-blog-backend" target="_blank">Backend Code</a>
                    <span style="color:var(--gray);">|</span>
                    <a class='view-code' href="https://github.com/shinhosuck/reactJS-pet-blog/tree/main/pet_blog" target="_blank">Frontend Code</a>
                </div>
                <p class="project-text-content">
                    This is a pet blog site where visitors can register and login to blog about their favorite furry friends. 
                    The blogger can choose a new topic to blog about or respond to an existing one.
                </p>
                <a class="see-website-button" href="https://reactjs-pet-blog.netlify.app/" target="_blank">View Project</a>
            </div>
        </div>

        <div class="project">
            <div class="project-img-wrapper">
                <img class="lg-image" src="{% static 'about_me/images/projects_images/e-commerce.webp' %}" alt="">
                <img class="sm-image" src="{% static 'about_me/images/projects_images/small-e-commerce.webp' %}" alt="">
                <div class="img-color-overlay"></div>
            </div>
            <div class="project-text-wrapper">
                <h3 class="project-name-header">
                    <span class="project-name">Ecommerce</span>
                    <span class="project-name-divider">|</span>
                    <span class="project-date">Oct 2023</span>
                </h3>
                <div class="project-tech-stacks-container">
                    <h4 class="project-tech-stack">Tech Stacks</h4>
                    <ul class="tech-stacks-used">
                        <li>Python,</li>
                        <li>Django,</li>
                        <li>HTML,</li>
                        <li>CSS,</li>
                        <li>Javascript</li>
                    </ul>
                </div>
                <div class="project-view-code-container">
                    <a class='view-code' href="https://github.com/shinhosuck/e-commerce" target="_blank">View Code</a>
                </div>
                <p class="project-text-content">
                    This is an online store where visitors can register and login to purchase products ranging 
                    from desktop PCs to various electronics accessories. The store uses the Stripe payment system, 
                    which accepts all major credit cards, including debit cards.
                </p>
                <a class="see-website-button" href="https://aiaimarket.pythonanywhere.com" target="_blank">View Project</a>
            </div>
        </div>

        <div class="project">
            <div class="project-img-wrapper">
                <img class="lg-image" src="{% static 'about_me/images/projects_images/cloud-music.webp' %}" alt="">
                <img class="sm-image" src="{% static 'about_me/images/projects_images/small-cloud-music.webp' %}" alt="">
                <div class="img-color-overlay"></div>
            </div>
            <div class="project-text-wrapper">
                <h3 class="project-name-header">
                    <span class="project-name">Cloud Music</span>
                    <span class="project-name-divider">|</span>
                    <span class="project-date">Mar 2023</span>
                </h3>
                <div class="project-tech-stacks-container">
                    <h4 class="project-tech-stack">Tech Stacks</h4>
                    <ul class="tech-stacks-used">
                        <li>Python,</li>
                        <li>Django,</li>
                        <li>HTML,</li>
                        <li>CSS,</li>
                        <li>JavaScript</li>
                    </ul>
                </div>
                <div class="project-view-code-container">
                    <a class='view-code' href="https://github.com/shinhosuck/myCloudMusic" target="_blank">View Code</a>
                </div>
                <p class="project-text-content">
                    This is a cloud music site where visitors can register and login to create music albums. 
                    Users can upload album covers to create albums and then upload songs to their albums.
                </p>
                <a class="see-website-button" href="https://cloudmusic.pythonanywhere.com" target="_blank">View Project</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

about_me/templates/about_me/nav.html
{% load static %}

    <nav class="navbar">
        <div class="nav-links-container">
            <div class="brand-name">
                <h4 class="brand-link">ericanderson</h4>
            </div>
            <div class="nav-toggle-btn">
                <i class="fa fa-bars toggle-bars-btn"></i>
                <i class="fa fa-times toggle-times-btn"></i>
            </div>
            <div class="nav-links">
                <a href="#contact-me" class="nav-link">
                    <i class="fa-solid fa-envelope"></i>
                    Contact
                </a>
                <a href="https://docs.google.com/document/d/1PCKXsHPvmur7mJHSiufv_Gid5Axo4LAi/edit?usp=sharing&ouid=112487098966462460918&rtpof=true&sd=true" target="_blank" class="nav-link">
                    <i class="fa-solid fa-file"></i>
                    Resume
                </a>
                <a class="nav-link" href="https://github.com/shinhosuck" target="_blank">
                    <i class="fab fa-github nav-link"></i>
                    GitHub
                </a>
                <a class="nav-link" href="https://www.linkedin.com/in/eric-anderson-a6b906214/" target="_blank">
                    <i class="fab fa-linkedin-in"></i>
                    LinkedIn
                </a>
            </div>
        </div>
        <div id="about" class="hero-container">
            <div class="hero-image">
                <img src="{% static 'about_me/images/person.webp' %}" alt="">
            </div>
            <div class="hero-text-container">
                <div class="hero-header">
                    <h1 class="hero-text-header">
                        Nice to meet you!
                        <span>I'm <span>Eric Anderson</span>.</span>
                    </h1>
                </div>
                <div class="hero-text-content">
                    <p>
                        I'm a Web Developer originally from San Diego, 
                        California, now based in Baguio City, Philippines. 
                        I'm passionate about crafting web applications that 
                        create meaningful connections with users.
                    </p>
                </div>
                <a class="hero-contact-me-btn" href="#contact-me">Contact Me</a>
            </div>
        </div>
    </nav>

   

about_me/templates/about_me/new_message_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML Email</title>
</head>
<body>
    <div class="container" stle="width: 100%;max-width:600px;margin:0 auto;">
        <table style="padding: 1rem; width: 100%;">
            <tr>
                <td style="padding: 1rem 0; max-width: 400px; font-size: 1.2rem;">
                    <p>You have a new message from {{ email }}.</p>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>

about_me/templates/about_me/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML Email</title>
</head>
<body>
    <div class="container" stle="width: 100%;max-width:600px;margin:0 auto;">
        <table style="padding: 1rem; width: 100%;">
            <tr>
                <th style="text-align: start; font-size: 1.5rem;">
                    Eric Anderson
                </th>
            </tr>
            <tr>
                <td style="padding: 1rem 0; font-size: 1.2rem; max-width: 400px;">
                    <span style="font-weight: bold; font-size: 1.2rem;">{{ name }}</span>, thank you for the message!
                </td>
            </tr>
            <tr>
                <td>
                    <img style="width: 400px; height: auto; display: block;" src="https://andersonportfolio.pythonanywhere.com/static/about_me/images/person.webp" alt="">
                </td>
            </tr>
            <tr>
                <td style="padding: 1rem 0; max-width: 400px; font-size: 1.2rem;">
                    <p>
                        Thank you for reaching out! I appreciate your message 
                        and will get back to you as soon as possible.
                    </p>
                </td>
            </tr>
            <tr>
                <td style="padding: 1rem 0; max-width: 400px; font-size: 1.2rem;">
                    If you have any further questions, feel free to let me know.
                </td>
            </tr>
            <tr>
                <td style="padding: 1rem 0; max-width: 400px; font-size: 1.2rem;">
                    Best regards,
                    Eric M. Anderson
                </td>
            </tr>
            <tr>
                <td style="padding: 1rem 0;">
                    <a href="https://andersonportfolio.pythonanywhere.com/" 
                        style="
                            padding: 0.8rem 1.4rem;
                            color: #ffffff;
                            background: #18bcd1;
                            border-radius: 30px;
                            text-decoration: none;
                            font-size: 1.1rem;
                        "
                    >
                        See portfolio
                    </a>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>